# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62bf1fdd2ecc647951bddd37d103fef18b749226c5f8a4728160a28c4f7d56069663d387ba490c8331523283c2c362c499f19cfe5a4caea46a074ebee44e1867

test:
  secret_key_base: 26f83b78a8be3c7740ba1231d2b83423ac281196ca46540e5f66e848841fbf51b78f8809bc7b6a13d00a2a994857aab3fcffd286d644c4c2fa14e6403d0636b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
